### ISSUE TITLE
Lincense

### ISSUE THREAD

**Issue by chrisdevh** [fredrikpersson92/minihass#4]
@fredrikpersson92 : Another suggestion. Many projects on github have published the code under a specific license to use. For example Home Assistant published under Apache License 2.0 The button-card project on which your work is based on is publishing oder MIT, just to name two of them. What do you think? Do you want to include a license? 

It is pretty easy to include on github. Just push the file `LICENSE` without anything further at the ending and paste the according license inside that file. 

Button Card: https://github.com/custom-cards/button-card/blob/master/LICENSE
Home Assistant: https://github.com/home-assistant/core/blob/dev/LICENSE.md

**Comment by fredrikpersson92** [comment]
Hey, I could not find any info on what to do here. Could you help me out?

**Comment by chrisdevh** [comment]
Hi. Sure I try to help here. Github provided a very good explaination here: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository  and provided a side to easly choose a license. For example button card choosed the MIT license.

**Comment by legovaer** [comment]
I would recommend the MIT license as it is a more permissive license than Apache 2.0. Basically, you can do whatever you want with MIT-licensed software, provided you add a copy of the original MIT license and copyright notice to it.

Apache is stricter because it requires you to list all the modifications you make to the original software. A copy of the license, with copyright and attribution notices, must be included in the source code and any modifications. A specific section on contributions outlines the conditions for accepting external contributions to the project. The MIT license requires a copyright notice, but it does not have explicit requirements for the license or attribution notices.

Apache covers patent rights. It requires contributors to grant a license to any patents they hold that are relevant to the software. The MIT license does not. Apache allows users to sublicense the software under the same license terms. The MIT license does not address sub-licensing.

Apache includes provisions related to trademarks, requiring explicit permission from the license holder to use any trademark associated with the software. The MIT license does not. Also, you can’t name your product in any way that hints at the product being endorsed by Apache. 

While both licenses allow software to be combined with projects under different licenses, Apache has more restrictions in terms of license compatibility compared to the MIT license.

The MIT license is gaining popularity with developers due to its short and clear license agreement that makes it simple and flexible to use. The Apache license agreement provides more protection for patents, contributions, and trademarks, but is far longer.
